/*
 * Release number. OS, arch, branch, and git describe come from buildstamp.h,
 * generated by posix/Makefile and by mk (via stamp.rc).
 *
 * lux -v prints:
 *   lux <version> <os>/<arch> <branch> <git-describe> [+sqlite] ...
 */
#define LUX_VERSION "1.2.0"

#include "buildstamp.h"
